Added new PostNL connection to the GCL
happy-geeks/geeks-core-library pull request #14
Opened 2022-02-02 15:16 UTC by alexxxx1992

2022-02-03 13:48 UTC, GilianJuice requested changes

2022-02-03 13:48 UTC, GilianJuice commented on GeeksCoreLibrary/Modules/PostalServices/PostNL/Controllers/PostNLController.cs
> +    [Route("api/post-nl")]
Graag niet `/api` gebruiken, want de GCL is geen API. Kun je hier `/postal-services/post-nl` van maken a.u.b.?

2022-02-03 13:48 UTC, GilianJuice commented on GeeksCoreLibrary/Modules/PostalServices/PostNL/Controllers/PostNLController.cs
> +                ulong countryId = UInt64.Parse(orderCountryCode);
Waarom doe je hier een nieuwe `UInt64.Parse`? Dat heeft geen zin. In de `UInt64.TryParse` die je in de if-statement doet, staat een out parameter. Die parameter bevat al de juiste waarde, gebruik die aub dan ook. Als je er dit van maakt:
`if (UInt64.TryParse(orderCountryCode, out var countryId))`
Dan kun je regels 39 en 43 helemaal weghalen en werkt het nog steeds.

2022-02-03 13:48 UTC, GilianJuice commented on GeeksCoreLibrary/Modules/PostalServices/PostNL/Controllers/PostNLController.cs
> +                var postNLDetails = await wiserItemsService.GetItemDetailsAsync(1118);
Hier staat een hard-coded ID, dat kan nooit goed zijn. Graag dit nakijken en verbeteren.

2022-02-03 13:48 UTC, GilianJuice commented on GeeksCoreLibrary/Modules/PostalServices/PostNL/Controllers/PostNLController.cs
> +                orderDetails.SetDetail("country_code", GetCountryCode(orderDetails, "country"));
Dit kan nooit goed werken. De functie `GetCountryCode` is een async functie. Graag hier een `await` voor zetten

2022-02-03 13:48 UTC, GilianJuice commented on GeeksCoreLibrary/Modules/PostalServices/PostNL/Controllers/PostNLController.cs
> +        private async Task<string> GetCountryCode(WiserItemModel orderDetails, string entityName)
Async functies moeten altijd de suffix `Async` hebben, deze graag hernoemen naar `GetCountryCodeAsync`.

2022-02-03 13:48 UTC, GilianJuice commented on GeeksCoreLibrary/Modules/PostalServices/PostNL/Controllers/PostNLController.cs
> +        public async Task<IActionResult> GenerateShippingLabel([FromQuery] string encryptedOrderIds)
Async functies moeten altijd de suffix `Async` hebben, deze graag hernoemen naar `GenerateShippingLabelAsync`.

2022-02-03 13:48 UTC, GilianJuice commented on GeeksCoreLibrary/Modules/PostalServices/PostNL/Controllers/PostNLController.cs
> +                var postNLDetails = await wiserItemsService.GetItemDetailsAsync(1118);
Daarnaast staat er _veel_ te veel code in deze functie. Een controller mag niets anders doen dan het verwerken van de input, aanroepen van services en zorgen voor de juiste output. Deze code moet allemaal in een service staan en dan moet je die service aanroepen in de controller.

Het kan best zijn dat dit in het originele project waar je dit vandaan had zo stond, maar in de GCL moet dit gewoon goed zijn, dus dat is geen excuus. Dan had je het in de GCL meteen moeten verbeteren

2022-02-03 13:48 UTC, GilianJuice commented on GeeksCoreLibrary/Modules/PostalServices/PostNL/Controllers/PostNLController.cs
> +        private async Task<string> GetCountryCode(WiserItemModel orderDetails, string entityName)
Deze functie hoort overigens ook niet thuis in de controller. Graag verplaatsen naar een service.

2022-02-03 13:48 UTC, GilianJuice commented on GeeksCoreLibrary/Modules/PostalServices/PostNL/Interfaces/IPostNLService.cs
> +        public Task<ShipmentResponseModel> CreateTrackTraceLabel(string orderId, ShipmentRequestModel request);
Async functies moeten altijd de suffix Async hebben, deze graag hernoemen naar `CreateTrackTraceLabelAsync`. In interfaces geen public/protected/private modifiers gebruiken, het woord `public` hier weghalen.

2022-02-03 13:48 UTC, GilianJuice commented on GeeksCoreLibrary/Modules/PostalServices/PostNL/Interfaces/IPostNLService.cs
> +        public Task<BarcodeResponseModel> CreateNewBarcode(string orderId, PostNLService.ShippingLocations shippingLocation = PostNLService.ShippingLocations.Netherlands);
Async functies moeten altijd de suffix Async hebben, deze graag hernoemen naar CreateNewBarcodeAsync. In interfaces geen public/protected/private modifiers gebruiken, het woord public hier weghalen.

2022-02-03 13:48 UTC, GilianJuice commented on GeeksCoreLibrary/Modules/PostalServices/PostNL/Interfaces/IPostNLService.cs
> +        public Task<SettingsModel> GetSettings(PostNLService.ShippingLocations shippingLocation);
Async functies moeten altijd de suffix Async hebben, deze graag hernoemen naar GetSettingsAsync. In interfaces geen public/protected/private modifiers gebruiken, het woord public hier weghalen.

2022-02-03 13:48 UTC, GilianJuice commented on GeeksCoreLibrary/Modules/PostalServices/PostNL/Models/AddressModel.cs
> +        public string HouseNr { get; set; }
Geen afkortingen. Hernoemen naar `HouseNumber`.

2022-02-03 13:48 UTC, GilianJuice commented on GeeksCoreLibrary/Modules/PostalServices/PostNL/Models/AddressModel.cs
> +        public string HouseNrExt { get; set; }
Geen afkortingen. Hernoemen naar `HouseNumberExtension` of `HouseNumberAddition`.

2022-02-03 13:48 UTC, GilianJuice commented on GeeksCoreLibrary/Modules/PostalServices/PostNL/Models/AddressModel.cs
> +        public string HouseNr { get; set; }
Als dit zo moet heten vanwege serializen van JSON, dan kun je het attribuut `[JsonProperty("houseNr")]` toevoegen.

2022-02-03 13:48 UTC, GilianJuice commented on GeeksCoreLibrary/Modules/PostalServices/PostNL/Services/PostNLService.cs
> +            await databaseConnection.ExecuteAsync("DELETE FROM cust_postnl_log WHERE datetime < DATE_SUB(NOW(), INTERVAL 2 WEEK)");
In de GCL willen we geen tabelnamen direct in query's hebben staan. Kun je hier een constante van maken en dan die constante in de query zetten?

2022-02-03 13:48 UTC, GilianJuice commented on GeeksCoreLibrary/Modules/PostalServices/PostNL/Services/PostNLService.cs
> +                await databaseConnection.InsertOrUpdateRecordBasedOnParametersAsync("cust_postnl_log", 0UL);
In de GCL willen we geen tabelnamen direct in query's hebben staan. Kun je hier een constante van maken en dan die constante in de query zetten?

2022-02-03 13:48 UTC, GilianJuice commented on GeeksCoreLibrary/Modules/PostalServices/PostNL/Services/PostNLService.cs
> +        private async Task CleanLogs()
Async functies moeten altijd de suffix Async hebben, deze graag hernoemen.

2022-02-03 13:48 UTC, GilianJuice commented on GeeksCoreLibrary/Modules/PostalServices/PostNL/Services/PostNLService.cs
> +        public async Task<SettingsModel> GetSettings(ShippingLocations shippingLocation)
Async functies moeten altijd de suffix Async hebben, deze graag hernoemen.

2022-02-03 13:48 UTC, GilianJuice commented on GeeksCoreLibrary/Modules/PostalServices/PostNL/Services/PostNLService.cs
> +        public async Task<BarcodeResponseModel> CreateNewBarcode(string orderId, ShippingLocations shippingLocation = ShippingLocations.Netherlands)
Async functies moeten altijd de suffix Async hebben, deze graag hernoemen.

2022-02-03 13:48 UTC, GilianJuice commented on GeeksCoreLibrary/Modules/PostalServices/PostNL/Services/PostNLService.cs
> +        public async Task<ShipmentResponseModel> CreateTrackTraceLabel(string orderId, ShipmentRequestModel request)
Async functies moeten altijd de suffix Async hebben, deze graag hernoemen.

2022-02-03 13:48 UTC, GilianJuice commented on GeeksCoreLibrary/Modules/PostalServices/PostNL/Services/PostNLService.cs
> +                await databaseConnection.InsertOrUpdateRecordBasedOnParametersAsync("cust_postnl_log", 0UL);
In de GCL willen we geen tabelnamen direct in query's hebben staan. Kun je hier een constante van maken en dan die constante in de query zetten?

2022-02-03 13:48 UTC, GilianJuice commented on GeeksCoreLibrary/Modules/PostalServices/PostNL/Services/PostNLService.cs
> +            await databaseConnection.ExecuteAsync("DELETE FROM cust_postnl_log WHERE datetime < DATE_SUB(NOW(), INTERVAL 2 WEEK)");
Daarnaast ook graag deze tabel een andere naam geven. De prefix `cust_` is, zoals de naam al zegt, voor custom tabellen bij klanten. Tabellen die de GCL/JCL gebruikt mogen deze prefix nooit hebben. Deze tabel kan dan gewoon `postnl_log` heten bijvoorbeeld.

2022-02-15 12:22 UTC, GilianJuice requested changes
Het ziet er een stuk beter uit. Alleen nog een paar kleine dingen die jij en/of ik de vorige keer over het hoofd hadden gezien. Kun je die nog aanpassen? Dan zijn vooral syntax dingen, zodat alles helemaal volgens onze richtlijnen en de rest van de GCL is.

2022-02-15 12:22 UTC, GilianJuice commented on GeeksCoreLibrary/Modules/PostalServices/PostNL/Interfaces/IPostNLService.cs
> +        Task<string> GenerateShippingLabel(string encryptedOrderIds);
Je bent hier nog vergeten de `Async` suffix toe te voegen, kun je dat nog doen?

2022-02-15 12:22 UTC, GilianJuice commented on GeeksCoreLibrary/Modules/PostalServices/PostNL/Models/CustomsContentModel.cs
> +        public string HSTariffNr { get; set; }
Kun je hier ook de naam aanpassen zodat er geen afkortingen meer in staan en geen meerdere hoofdletters achter elkaar?

2022-02-15 12:22 UTC, GilianJuice commented on GeeksCoreLibrary/Modules/PostalServices/PostNL/Models/CustomsModel.cs
> +        public string InvoiceNr { get; set; }
Hier ook `InvoiceNumber` van maken a.u.b.

2022-02-15 12:22 UTC, GilianJuice commented on GeeksCoreLibrary/Modules/PostalServices/PostNL/Models/MessageModel.cs
> +        public string MessageID { get; set; }
Hier `MessageId` van maken aub (kleine letter D).

2022-02-15 12:22 UTC, GilianJuice commented on GeeksCoreLibrary/Modules/PostalServices/PostNL/Models/PostNlSettings.cs
> +        public string PostNlTariffNr { get; set; }
Hier `PostNlTariffNumber` van maken aub.

2022-02-15 12:22 UTC, GilianJuice commented on GeeksCoreLibrary/Modules/PostalServices/PostNL/Services/PostNLService.cs
> +            if (ulong.TryParse(orderCountryCode, out var countryId))
Hier graag `UInt64.TryParse` van maken. In onze richtlijnen staat ook dat je voor het aanroepen van (static) functies altijd de CLR types moet gebruiken (dat zijn de types van .NET, zoals `Int32`, `Int64`, `String` (met hoofdletter) etc) en bij variabelen en properties de C# types moet gebruiken (dat zijn de types met kleine letters, zoals `int`, `long`, `string` etc).

2022-02-15 12:22 UTC, GilianJuice commented on GeeksCoreLibrary/Modules/PostalServices/PostNL/Services/PostNLService.cs
> +            return $"<ul><li>{String.Join("</li><li>", result)}</li></ul>";
Dit was me eerder niet opgevallen, maar de HTML die hier teruggegeven wordt, was specifiek voor de Wiser inrichting van Beachlife gemaakt. Dit is niet handig om zo in de GCL te laten staan. Deze functie zou gewoon de variabele `result` direct moeten teruggeven, zonder daar HTML van te maken. Kun je dat aanpassen?

2022-02-17 12:26 UTC, GilianJuice requested changes

2022-02-17 12:26 UTC, GilianJuice commented on GeeksCoreLibrary/Modules/PostalServices/PostNL/Services/PostNLService.cs
> +            return $"<ul><li>{String.Join("</li><li>", result)}</li></ul>";
@alexxxx1992 Je bent deze nog vergeten aan te passen in je laatste commit. Als je dit nog wilt aanpassen, dan keur ik hem daarna goed.

2022-02-17 15:03 UTC, alexxxx1992 commented
Hoi Gilian,

Wat moet ik hier precies aanpassen?

Want in mijn laatste comment heb ik er al voor gezorgd dat er geen HTML
meer wordt teruggegeven maar gewoon het result.

[image: image.png]

mvg,
Alex


Op do 17 feb. 2022 om 13:26 schreef Gilian ***@***.***>:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In
> GeeksCoreLibrary/Modules/PostalServices/PostNL/Services/PostNLService.cs
> <https://github.com/happy-geeks/geeks-core-library/pull/14#discussion_r808994260>
> :
>
> > +                        {
> +                            ItemId = ulong.Parse(orderId),
> +                            Content = Convert.FromBase64String(label.Content),
> +                            Extension = ".pdf",
> +                            FileName = $"{label.Labeltype}.pdf",
> +                            ContentType = "application/pdf",
> +                            PropertyName = "postnl_label",
> +                            Title = barcode
> +                        });
> +                    }
> +                }
> +
> +                result.Add($"Order {orderId}: Er is succesvol een verzendlabel gegenereerd en verstuurd naar de klant, deze kan gevonden worden op de tab 'PostNL' van deze order. De track&trace code is: {barcode}");
> +            }
> +
> +            return $"<ul><li>{String.Join("</li><li>", result)}</li></ul>";
>
> @alexxxx1992 <https://github.com/alexxxx1992> Je bent deze nog vergeten
> aan te passen in je laatste commit. Als je dit nog wilt aanpassen, dan keur
> ik hem daarna goed.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/happy-geeks/geeks-core-library/pull/14#pullrequestreview-885883292>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AJALL654QJD7IK2QABIVXBTU3TSPZANCNFSM5NMKOULQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-02-22 12:39 UTC, GilianJuice approved these changes

2022-02-22 12:39 UTC, merged