Adding default values
happy-geeks/geeks-core-library pull request #187
Opened 2022-09-22 11:16 UTC by JeremyMullerr

It is now possible to add default values by adding a "?" and then the default value to a variable within a Wiser HTML template.
For example {variable?1234}
[GCL: default waarde op kunnen geven voor variabelen {naam:defaultvalue}]

Asana ticket:
(https://app.asana.com/0/1201027711166952/1202879712279705)

2022-09-23 07:42 UTC, HansJuice requested changes

2022-09-23 07:42 UTC, HansJuice commented on GeeksCoreLibrary/Modules/GclReplacements/Interfaces/IStringReplacementsService.cs
> +        /// Searched input string for variables with default values and replaces them with those default values.
Ik denk dat hier een typefout staat. Volgens mij bedoelde je hier "Searches input string" i.p.v. "Searched" (dus searches met een 's' i.p.v. een 'd').

2022-09-23 07:42 UTC, HansJuice commented on GeeksCoreLibrary/Modules/GclReplacements/Interfaces/IStringReplacementsService.cs
> +        string HandledVariablesDefaultValues(string input, string prefix = "{", string suffix = "}");
Ik vind de benaming van deze functie misleidend. Het woord "`Handled`" duidt aan dat dit een functie is die bijhoudt welke "`DefaultValues`" al behandeld zijn. Ik denk dat de naam "`HandleVariablesDefaultValues`" beter is.

2022-09-23 07:42 UTC, HansJuice commented on GeeksCoreLibrary/Modules/GclReplacements/Services/StringReplacementsService.cs
> +                    if (!variable.DefaultValue.IsNullOrEmpty())
Graag hier gewoon `String.IsNullOrEmpty(variable.DefaultValue)` gebruiken. Deze extension method zorgt voor een extra `using` bovenin voor één functie (`using Microsoft.IdentityModel.Tokens`), en bovendien zorgt dit voor inconsistentie omdat we dit nergens anders gebruiken.

2022-09-26 08:02 UTC, JeremyMullerr commented
Bij deze de benodigde aanpassingen gedaan.

2022-09-30 07:11 UTC, HansJuice approved these changes

2022-09-30 07:11 UTC, merged