Feature/whatsapp communication
happy-geeks/geeks-core-library pull request #226
Opened 2022-11-17 14:20 UTC by Mohamadalsamour99

Whatsapp functionaliteit is toe gevoegd zodat berichten naast sms, ook via whatsapp kunnen verstuurd worden. Keuze tussen providers: Cm en Meta.

2022-11-18 10:18 UTC, HansJuice commented
Er zitten merge conflicts in deze branch die eerst opgelost moeten worden.

2022-11-18 10:19 UTC, HansJuice requested changes
Er zitten merge conflicts in deze pull request die eerst opgelost moeten worden.

2022-11-22 09:01 UTC, GilianJuice requested changes

2022-12-13 09:53 UTC, GilianJuice requested changes

2022-12-13 09:53 UTC, GilianJuice commented on GeeksCoreLibrary/Modules/Communication/Models/AttachmentUrlsModel.cs
> +using DocumentFormat.OpenXml.Office2019.Excel.RichData2;
Deze using lijkt per ongeluk toegevoegd en is niet nodig, graag weghalen.

2022-12-13 09:53 UTC, GilianJuice commented on GeeksCoreLibrary/Modules/Communication/Services/CommunicationsService.cs
> +             }
Hier gaat iets niet goed met de uitlijning van de code, graag goedzetten.

2022-12-13 09:53 UTC, GilianJuice commented on GeeksCoreLibrary/Modules/Communication/Services/CommunicationsService.cs
> +                    throw new Exception("image/document/audio/video has not been sent..." + response.ErrorMessage);
Aub geen string concattenation gebruiken, maar interpolation.

2022-12-13 09:53 UTC, GilianJuice commented on GeeksCoreLibrary/Modules/Communication/Services/CommunicationsService.cs
> +                        request.AddHeader("Authorization", "Bearer " + apiToken);
Aub geen string concattenation gebruiken, maar interpolation.

2022-12-13 09:53 UTC, GilianJuice commented on GeeksCoreLibrary/Modules/Communication/Services/CommunicationsService.cs
> +                throw new Exception("message content has not been sent..." + response.ErrorMessage);
Aub geen string concattenation gebruiken, maar interpolation.

2022-12-30 08:09 UTC, HansJuice requested changes
Graag de aangepaste bestanden nog een keertje nalopen om alle ongebruikte `using` directives weg te halen. Met name `CommunicationsService.cs` heeft veel `using` directives die weg kunnen. Rider kan daar goed mee helpen, want die maakt ze automatisch grijs als ze weg kunnen, en kan ze zelfs voor je weghalen.

![image](https://user-images.githubusercontent.com/35447467/210048602-51b37dd4-5901-4da8-8b1d-bd9dc43cfd6e.png)

Wat mij betreft zijn de aanpassingen daarna goed, dus dit is het laatste.

2023-01-10 10:57 UTC, GilianJuice approved these changes

2023-01-10 10:57 UTC, merged