Added 2 factor authentication to the Account component in the GCL
happy-geeks/geeks-core-library pull request #293
Opened 2023-02-02 16:31 UTC by JeremyMullerr

Added 2 factor authentication to the Account component in the GCL
Asana link:
https://app.asana.com/0/1201027711166952/1201613272599806

2023-02-08 08:10 UTC, MarkVanDijkHG commented on GeeksCoreLibrary/Components/Account/Interfaces/IAccountsService.cs
> +        Task Save2FaKeyAsync(ulong userId, string user2FaKey);
Graag hier geen afkortingen gebruiken (afkorting van "Id" mag wel).

2023-02-08 08:10 UTC, MarkVanDijkHG commented on GeeksCoreLibrary/Components/Account/Interfaces/IAccountsService.cs
> +        Task<String> Get2FaKeyAsync(ulong userId, string entityType);
Graag hier geen afkortingen gebruiken (afkorting van "Id" mag wel).

2023-02-08 08:12 UTC, MarkVanDijkHG commented on GeeksCoreLibrary/Components/Account/Services/AccountsService.cs
> +        public async Task Save2FaKeyAsync(ulong userId, string user2FAKey)
Graag hier geen afkortingen gebruiken (afkorting van "Id" mag wel).

2023-02-08 08:12 UTC, MarkVanDijkHG commented on GeeksCoreLibrary/Components/Account/Services/AccountsService.cs
> +        public async Task<String> Get2FaKeyAsync(ulong userId, string entityType)
Graag hier geen afkortingen gebruiken (afkorting van "Id" mag wel).

2023-02-08 08:26 UTC, MarkVanDijkHG commented on GeeksCoreLibrary/Components/Account/Account.cs
> +            var googleAuthKey = await AccountsService.Get2FaKeyAsync(Convert.ToUInt64(sessionUserId), Settings.EntityType);
Hier graag geen afkorting voor gebruiken.

2023-02-08 08:26 UTC, MarkVanDijkHG commented on GeeksCoreLibrary/Components/Account/Account.cs
> +                    var googleAuthKey = await AccountsService.Get2FaKeyAsync(loggedInUserId, Settings.EntityType);
Hier graag geen afkorting voor gebruiken.

2023-02-08 08:27 UTC, MarkVanDijkHG commented on GeeksCoreLibrary/Components/Account/Services/AccountsService.cs
> +            var query = @"INSERT INTO wiser_itemdetail (item_id, `key`, `value`)
Graag de "WiserTableNames" class gebruiken voor de tabel naam.

2023-02-08 08:27 UTC, MarkVanDijkHG commented on GeeksCoreLibrary/Components/Account/Services/AccountsService.cs
> +            var query = @"SELECT value FROM wiser_itemdetail WHERE item_id = ?userId AND `key` = 'User2FAKey'";
Graag de "WiserTableNames" class gebruiken voor de tabel naam.

2023-02-22 08:30 UTC, MarkVanDijkHG commented on GeeksCoreLibrary/Components/Account/Services/AccountsService.cs
> +            var query = @"INSERT INTO wiser_itemdetail (item_id, `key`, `value`)
Dit is nu aangepast naar het gebruik van een parameter. Wat ik hiermee bedoelde is via string interpolation. Bij andere queries in de GCL kan je zien hoe dit daar wordt toegepast.

2023-02-22 08:30 UTC, MarkVanDijkHG commented on GeeksCoreLibrary/Components/Account/Services/AccountsService.cs
> +            var query = @"SELECT value FROM wiser_itemdetail WHERE item_id = ?userId AND `key` = 'User2FAKey'";
Dit is nu aangepast naar het gebruik van een parameter. Wat ik hiermee bedoelde is via string interpolation. Bij andere queries in de GCL kan je zien hoe dit daar wordt toegepast.

2023-02-22 08:32 UTC, MarkVanDijkHG requested changes
Nog een aantal punten zijn niet goed verwerkt (zie ook de voorgaande comments die nog niet zijn afgevinkt). Ook is nog een merge conflict die opgelost moet worden.

2023-02-23 10:11 UTC, JeremyMullerr commented
Merge conflict opgelost en de laatste comments weggewerkt

2023-02-23 13:46 UTC, MarkVanDijkHG approved these changes

2023-03-15 16:21 UTC, merged