Added branchName to caching keys (renamed all vars to identical naming 'cacheName')
happy-geeks/geeks-core-library pull request #458
Opened 2023-10-26 12:52 UTC by celineloos1997

2023-10-31 13:45 UTC, MarkVanDijkHG requested changes
Please check if the changes at the comments are on purpose.

2023-10-31 13:58 UTC, celineloos1997 commented on GeeksCoreLibrary/Components/OrderProcess/Services/CachedOrderProcessesService.cs
> +using System.Linq;
This using has been added without my knowledge. I will remove this using.

2023-10-31 14:04 UTC, celineloos1997 commented on GeeksCoreLibrary/Core/Services/CachedWiserItemsService.cs
> +using GeeksCoreLibrary.Modules.Branches.Services;
This using has been added without my knowledge. I will remove this using.

2023-11-01 10:18 UTC, HansHappyHorizon approved these changes

2023-11-01 10:18 UTC, merged