Fix/optimized loading of assamblys with nopsp
happy-geeks/geeks-core-library pull request #554
Opened 2024-04-15 07:28 UTC by ferryvandegraaf

# Describe your changes

Please include a summary of the changes and relevant motivation and context.

## Type of change

Please check only ONE option.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## How was this tested?

Please describe how you tested your changes and how you confirmed this functionality is not a breaking change.

# Checklist before requesting a review
- [x] I have reviewed and tested my changes
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I selected `develop` as the base branch and not `main`, or the pull request is a hotfix that needs to be done directly on `main`
- [x] I double checked all my changes and they contain no temporary test code, no code that is commented out and no changes that are not part of this branch
- [ ] I added new unit tests for my changes if applicable

# Related pull requests

Add any open pull requests from other projects that are related to this pull request that should be merged along with this one. If there are none, you can simply say "none" or "N/A", or just leave this section empty.

# Link to Asana ticket

Add a link to the Asana ticket. Note that **_ONLY_** the URL should be added, not the name of the ticket!

2024-04-17 08:23 UTC, HansHappyHorizon commented
Please fill out the entire form instead of only checking some boxes (summary of changes and explanation of how the changes were tested).

2024-04-18 13:15 UTC, GilianJuice requested changes
I can't approve this. This PR contains a lot of changed that have nothing to do with what it said in the description.

To be honest, I also don't see much point in the change of not loading the NoPSP assembly. I don't see how this change makes a lot of impact, it might improve the speed by 1 millisecond, but it causes the problem that we can't add settings to NoPSP in the future. Why exactly did you make this change? Did you notice bad performance?

If it does actually make a noticable improvement, I can accept it, but not with all these other changes that have nothing to do with it.

2024-04-18 13:15 UTC, GilianJuice commented on GeeksCoreLibrary/Components/OrderProcess/Services/OrderProcessesService.cs
> +                    if (paymentMethodSettings.PaymentServiceProvider.Type != PaymentServiceProviders.NoPsp && basketToConceptOrderMethod == OrderProcessBasketToConceptOrderMethods.Convert && copyBask
This code is from a pull request from Rinus (https://github.com/happy-geeks/geeks-core-library/pull/548), why is it also in yours? I denied that PR from Rinus, so please remove that code here as well.

2024-04-18 13:15 UTC, GilianJuice commented on GeeksCoreLibrary/Core/Extensions/DataRowExtensions.cs
> +                        result.TryAdd(TrimPrefix(columnName[..^(withDate ? NormalEncryptWithDateSuffix : NormalEncryptSuffix).Length], requiredColumnNamePrefix), value.UrlEncode());
What is all of this? This seems to have nothing to do with loading assembly for NoPSP.

2024-05-17 10:04 UTC, closed without merging