Bugfix/caching of paymentmethodsettings issue
happy-geeks/geeks-core-library pull request #556
Opened 2024-04-15 08:53 UTC by ferryvandegraaf

# Describe your changes

Please include a summary of the changes and relevant motivation and context.

## Type of change

Please check only ONE option.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## How was this tested?

Please describe how you tested your changes and how you confirmed this functionality is not a breaking change.

# Checklist before requesting a review
- [x] I have reviewed and tested my changes
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I selected `develop` as the base branch and not `main`, or the pull request is a hotfix that needs to be done directly on `main`
- [x] I double checked all my changes and they contain no temporary test code, no code that is commented out and no changes that are not part of this branch
- [ ] I added new unit tests for my changes if applicable

# Related pull requests

Add any open pull requests from other projects that are related to this pull request that should be merged along with this one. If there are none, you can simply say "none" or "N/A", or just leave this section empty.

# Link to Asana ticket

Add a link to the Asana ticket. Note that **_ONLY_** the URL should be added, not the name of the ticket!

2024-04-17 08:23 UTC, HansHappyHorizon commented
Please fill out the entire form instead of only checking some boxes (summary of changes and explanation of how the changes were tested).

2024-04-17 13:51 UTC, ferryvandegraaf commented
Description added.

2024-04-18 13:38 UTC, GilianJuice requested changes
Firstly, I don't see any changes for the first part of your description, about not caching payment settings anymore? Did you forget something or do I understand your description wrongly?

Secondly, this PR contains changes from other PRs that have nothing to do with what you described. They even contain changes from a different person. Please remove all changes that are not related.

2024-04-18 13:38 UTC, GilianJuice commented on GeeksCoreLibrary/Components/OrderProcess/Services/CachedOrderProcessesService.cs
> +                return await orderProcessesService.GetPaymentMethodAsync(paymentMethodId);
Please add brackets and spaces. It should be like this:
```C#
if (gclSettings.DefaultOrderProcessCacheDuration.TotalSeconds == 0)
{
    return await orderProcessesService.GetPaymentMethodAsync(paymentMethodId);
}
```

2024-07-18 11:14 UTC, GilianJuice commented
Closing this PR because it's outdated. If we ever want these changes, we'll copy them manually from In-vista's fork.

2024-07-18 11:14 UTC, closed without merging